name: ci

on:
    push:
        branches:
            - 'dev'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  script: |
                      docker build -f Dockerfiles/Dockerfile.feBuild -t ${{ secrets.DOCKER_HUB_USERNAME }}/fs-docker-fe:latest .
                      docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fs-docker-fe:latest
            # - name: Build and push
            #   uses: docker/build-push-action@v3
            #   with:
            #       context: ../../Dockerfiles/Dockerfile.feBuild
            #       push: true
            #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fs-docker:latest
            # - name: Build Image
            #   run: docker build -f Dockerfiles/Dockerfile.feBuild -t ${{ secrets.DOCKER_HUB_USERNAME }}/fs-docker-fe:latest .
            # - name: Push Image to Docker Hub
            #   run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fs-docker-fe:latest
